from __future__ import annotations
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Callable, Dict, List, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from ...models.trades400_error import Trades400Error
    from ...models.trades401_error import Trades401Error
    from ...models.trades403_error import Trades403Error
    from ...models.trades404_error import Trades404Error
    from ...models.trades406_error import Trades406Error
    from ...models.trades429_error import Trades429Error
    from ...models.trades500_error import Trades500Error
    from .trades_get_response import TradesGetResponse

class TradesItemRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /trades/{id}
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, Dict[str, Any]]) -> None:
        """
        Instantiates a new TradesItemRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/trades/{id}", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[TradesGetResponse]:
        """
        Returns a trade entity for a valid identifier.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[TradesGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from ...models.trades400_error import Trades400Error
        from ...models.trades401_error import Trades401Error
        from ...models.trades403_error import Trades403Error
        from ...models.trades404_error import Trades404Error
        from ...models.trades406_error import Trades406Error
        from ...models.trades429_error import Trades429Error
        from ...models.trades500_error import Trades500Error

        error_mapping: Dict[str, ParsableFactory] = {
            "400": Trades400Error,
            "401": Trades401Error,
            "403": Trades403Error,
            "404": Trades404Error,
            "406": Trades406Error,
            "429": Trades429Error,
            "500": Trades500Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .trades_get_response import TradesGetResponse

        return await self.request_adapter.send_async(request_info, TradesGetResponse, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Returns a trade entity for a valid identifier.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/vnd.api+json")
        return request_info
    
    def with_url(self,raw_url: str) -> TradesItemRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: TradesItemRequestBuilder
        """
        if not raw_url:
            raise TypeError("raw_url cannot be null.")
        return TradesItemRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class TradesItemRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

